export const uselessFacts: { id: number; fact: string }[] = [
    { id: 1, fact: "Bananas are berries, but strawberries aren't." },
    { id: 2, fact: "A group of flamingos is called a 'flamboyance'." },
    { id: 3, fact: "Wombat poop is cube-shaped." },
    { id: 4, fact: "Honey never spoils." },
    { id: 5, fact: "A duck's quack doesn't echo, and no one knows why." },
    { id: 6, fact: "Avocados are poisonous to birds." },
    { id: 7, fact: "The shortest war in history was between Britain and Zanzibar, lasting 38 minutes." },
    { id: 8, fact: "Cows have best friends and get stressed when separated." },
    { id: 9, fact: "Octopuses have three hearts." },
    { id: 10, fact: "A snail can sleep for three years." },
    { id: 11, fact: "It's impossible to hum while holding your nose." },
    { id: 12, fact: "The inventor of the Frisbee was turned into a Frisbee after he died." },
    { id: 13, fact: "There's a species of jellyfish that is immortal." },
    { id: 14, fact: "A crocodile cannot stick its tongue out." },
    { id: 15, fact: "Butterflies taste with their feet." },
    { id: 16, fact: "Mosquitoes are attracted to people who just ate bananas." },
    { id: 17, fact: "Sloths can hold their breath longer than dolphins can." },
    { id: 18, fact: "There are more stars in the universe than grains of sand on all the world's beaches." },
    { id: 19, fact: "Sea cucumbers can eject their internal organs to defend themselves." },
    { id: 20, fact: "Koalas have fingerprints almost identical to humans." },
    { id: 21, fact: "Alaska is the only state that can be typed on one row of a keyboard." },
    { id: 22, fact: "There are more fake flamingos in the world than real ones." },
    { id: 23, fact: "Elephants are the only animals that can't jump." },
    { id: 24, fact: "A bolt of lightning contains enough energy to toast 100,000 slices of bread." },
    { id: 25, fact: "The hashtag symbol is technically called an octothorpe." },
    { id: 26, fact: "Cleopatra lived closer in time to the moon landing than to the construction of the Great Pyramid." },
    { id: 27, fact: "A small child could swim through the veins of a blue whale." },
    { id: 28, fact: "A jiffy is an actual unit of time: 1/100th of a second." },
    { id: 29, fact: "The heart of a shrimp is located in its head." },
    { id: 30, fact: "A human could swim through the veins of a blue whale." },
    { id: 31, fact: "Dolphins have names for each other." },
    { id: 32, fact: "The total weight of ants on Earth once equaled the total weight of people." },
    { id: 33, fact: "A day on Venus is longer than a year on Venus." },
    { id: 34, fact: "The longest hiccuping spree lasted 68 years." },
    { id: 35, fact: "Cherophobia is the fear of fun." },
    { id: 36, fact: "Octopuses have nine brains." },
    { id: 37, fact: "The shortest commercial flight in the world lasts just 57 seconds." },
    { id: 38, fact: "Bubble wrap was originally intended to be wallpaper." },
    { id: 39, fact: "Banging your head against a wall for one hour burns 150 calories." },
    { id: 40, fact: "An apple, potato, and onion all taste the same if you eat them with your nose plugged." },
    { id: 41, fact: "The unicorn is the national animal of Scotland." },
    { id: 42, fact: "Pteronophobia is the fear of being tickled by feathers." },
    { id: 43, fact: "Humans share 50% of their DNA with bananas." },
    { id: 44, fact: "It's possible to lead a cow upstairs but not downstairs." },
    { id: 45, fact: "A group of porcupines is called a prickle." },
    { id: 46, fact: "Chewing gum while cutting onions can help prevent tears." },
    { id: 47, fact: "A small child could swim through the veins of a blue whale." },
    { id: 48, fact: "Dolphins have names for each other." },
    { id: 49, fact: "A single strand of spaghetti is called a spaghetto." },
    { id: 50, fact: "Kangaroos can't walk backwards." },
    { id: 51, fact: "Bananas are curved because they grow towards the sun." },
    { id: 52, fact: "The inventor of the Pringles can is now buried in one." },
    { id: 53, fact: "A flock of crows is known as a murder." },
    { id: 54, fact: "The Twitter bird's name is Larry." },
    { id: 55, fact: "Cows moo with regional accents." },
    { id: 56, fact: "The longest wedding veil was longer than 63 football fields." },
    { id: 57, fact: "A baby octopus is about the size of a flea when it's born." },
    { id: 58, fact: "A blue whale's tongue weighs as much as an elephant." },
    { id: 59, fact: "Scotland has 421 words for 'snow'." },
    { id: 60, fact: "The first oranges weren’t orange." },
    { id: 61, fact: "There's a world record for the most world records." },
    { id: 62, fact: "A cow-bison hybrid is called a 'beefalo'." },
    { id: 63, fact: "The inventor of the match was originally trying to create an explosive." },
    { id: 64, fact: "In Switzerland, it's illegal to own just one guinea pig." },
    { id: 65, fact: "The national animal of Scotland is the unicorn." },
    { id: 66, fact: "There are 293 ways to make change for a dollar." },
    { id: 67, fact: "Penguins propose to each other with a pebble." },
    { id: 68, fact: "The average person walks the equivalent of five times around the world in their lifetime." },
    { id: 69, fact: "A sneeze travels about 100 miles per hour." },
    { id: 70, fact: "There are more fake flamingos in the world than real ones." },
    { id: 71, fact: "You can’t hum while holding your nose." },
    { id: 72, fact: "Honey never spoils." },
    { id: 73, fact: "A crocodile cannot stick its tongue out." },
    { id: 74, fact: "A shrimp's heart is in its head." },
    { id: 75, fact: "It is physically impossible for pigs to look up into the sky." },
    { id: 76, fact: "The shortest war in history was between Britain and Zanzibar, lasting 38 minutes." },
    { id: 77, fact: "Giraffes have no vocal cords." },
    { id: 78, fact: "Bananas are berries, but strawberries aren’t." },
    { id: 79, fact: "Wombat poop is cube-shaped." },
    { id: 80, fact: "A group of flamingos is called a 'flamboyance'." },
    { id: 81, fact: "Octopuses have three hearts." },
    { id: 82, fact: "Sloths can hold their breath longer than dolphins can." },
    { id: 83, fact: "Mosquitoes are attracted to people who just ate bananas." },
    { id: 84, fact: "Butterflies taste with their feet." },
    { id: 85, fact: "Elephants are the only animals that can't jump." },
    { id: 86, fact: "There's a species of jellyfish that is immortal." },
    { id: 87, fact: "The inventor of the Frisbee was turned into a Frisbee after he died." },
    { id: 88, fact: "It's impossible to hum while holding your nose." },
    { id: 89, fact: "A snail can sleep for three years." },
    { id: 90, fact: "The heart of a shrimp is located in its head." },
    { id: 91, fact: "Cleopatra lived closer in time to the moon landing than to the construction of the Great Pyramid." },
    { id: 92, fact: "The hashtag symbol is technically called an octothorpe." },
    { id: 93, fact: "A bolt of lightning contains enough energy to toast 100,000 slices of bread." },
    { id: 94, fact: "A group of porcupines is called a prickle." },
    { id: 95, fact: "Humans share 50% of their DNA with bananas." },
    { id: 96, fact: "Pteronophobia is the fear of being tickled by feathers." },
    { id: 97, fact: "The unicorn is the national animal of Scotland." },
    { id: 98, fact: "Alaska is the only state that can be typed on one row of a keyboard." },
    { id: 99, fact: "Koalas have fingerprints almost identical to humans." },
    { id: 100, fact: "Sea cucumbers can eject their internal organs to defend themselves." },
    { id: 101, fact: "A single strand of spaghetti is called a spaghetto." },
  { id: 102, fact: "Ketchup was sold in the 1830s as medicine." },
  { id: 103, fact: "A group of flamingos is called a flamboyance." },
  { id: 104, fact: "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of iron." },
  { id: 105, fact: "Polar bears have black skin under their white fur." },
  { id: 106, fact: "The first oranges weren't orange." },
  { id: 107, fact: "There's a single mega-colony of ants that spans three continents." },
  { id: 108, fact: "Wombat poop is cube-shaped." },
  { id: 109, fact: "Oxford University is older than the Aztec Empire." },
  { id: 110, fact: "A group of crows is called a murder." },
  { id: 111, fact: "The longest English word is 189,819 letters long." },
  { id: 112, fact: "The world's oldest piece of chewing gum is over 9,000 years old." },
  { id: 113, fact: "Peanuts are not nuts, they are legumes." },
  { id: 114, fact: "A baby puffin is called a puffling." },
  { id: 115, fact: "Bananas are berries, but strawberries aren't." },
  { id: 116, fact: "The unicorn is the national animal of Scotland." },
  { id: 117, fact: "A group of porcupines is called a prickle." },
  { id: 118, fact: "A bolt of lightning contains enough energy to toast 100,000 slices of bread." },
  { id: 119, fact: "Humans share 50% of their DNA with bananas." },
  { id: 120, fact: "Pteronophobia is the fear of being tickled by feathers." },
  { id: 121, fact: "Alaska is the only state that can be typed on one row of a keyboard." },
  { id: 122, fact: "Koalas have fingerprints almost identical to humans." },
  { id: 123, fact: "Sea cucumbers can eject their internal organs to defend themselves." },
  { id: 124, fact: "A small child could swim through the veins of a blue whale." },
  { id: 125, fact: "A jiffy is an actual unit of time: 1/100th of a second." },
  { id: 126, fact: "The heart of a shrimp is located in its head." },
  { id: 127, fact: "A human could swim through the veins of a blue whale." },
  { id: 128, fact: "Dolphins have names for each other." },
  { id: 129, fact: "The total weight of ants on Earth once equaled the total weight of people." },
  { id: 130, fact: "A day on Venus is longer than a year on Venus." },
  { id: 131, fact: "The longest hiccuping spree lasted 68 years." },
  { id: 132, fact: "A crocodile cannot stick its tongue out." },
  { id: 133, fact: "Butterflies taste with their feet." },
  { id: 134, fact: "Sloths can hold their breath longer than dolphins can." },
  { id: 135, fact: "There are more stars in the universe than grains of sand on all the world's beaches." },
  { id: 136, fact: "Sea cucumbers can eject their internal organs to defend themselves." },
  { id: 137, fact: "Koalas have fingerprints almost identical to humans." },
  { id: 138, fact: "Alaska is the only state that can be typed on one row of a keyboard." },
  { id: 139, fact: "The unicorn is the national animal of Scotland." },
  { id: 140, fact: "Pteronophobia is the fear of being tickled by feathers." },
  { id: 141, fact: "A bolt of lightning contains enough energy to toast 100,000 slices of bread." },
  { id: 142, fact: "Humans share 50% of their DNA with bananas." },
  { id: 143, fact: "A group of porcupines is called a prickle." },
  { id: 144, fact: "A group of flamingos is called a flamboyance." },
  { id: 145, fact: "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of iron." },
  { id: 146, fact: "Polar bears have black skin under their white fur." },
  { id: 147, fact: "The first oranges weren't orange." },
  { id: 148, fact: "There's a single mega-colony of ants that spans three continents." },
  { id: 149, fact: "Wombat poop is cube-shaped." },
  { id: 150, fact: "Oxford University is older than the Aztec Empire." },
  { id: 151, fact: "A group of crows is called a murder." },
  { id: 152, fact: "The longest English word is 189,819 letters long." },
  { id: 153, fact: "The world's oldest piece of chewing gum is over 9,000 years old." },
  { id: 154, fact: "Peanuts are not nuts, they are legumes." },
  { id: 155, fact: "A baby puffin is called a puffling." },
  { id: 156, fact: "A single strand of spaghetti is called a spaghetto." },
  { id: 157, fact: "Ketchup was sold in the 1830s as medicine." },
  { id: 158, fact: "A group of flamingos is called a flamboyance." },
  { id: 159, fact: "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of iron." },
  { id: 160, fact: "Polar bears have black skin under their white fur." },
  { id: 161, fact: "The first oranges weren't orange." },
  { id: 162, fact: "There's a single mega-colony of ants that spans three continents." },
  { id: 163, fact: "Wombat poop is cube-shaped." },
  { id: 164, fact: "Oxford University is older than the Aztec Empire." },
  { id: 165, fact: "A group of crows is called a murder." },
  { id: 166, fact: "The longest English word is 189,819 letters long." },
  { id: 167, fact: "The world's oldest piece of chewing gum is over 9,000 years old." },
  { id: 168, fact: "Peanuts are not nuts, they are legumes." },
  { id: 169, fact: "A baby puffin is called a puffling." },
  { id: 170, fact: "A single strand of spaghetti is called a spaghetto." },
  { id: 171, fact: "Ketchup was sold in the 1830s as medicine." },
  { id: 172, fact: "A group of flamingos is called a flamboyance." },
  { id: 173, fact: "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of iron." },
  { id: 174, fact: "Polar bears have black skin under their white fur." },
  { id: 175, fact: "The first oranges weren't orange." },
  { id: 176, fact: "There's a single mega-colony of ants that spans three continents." },
  { id: 177, fact: "Wombat poop is cube-shaped." },
  { id: 178, fact: "Oxford University is older than the Aztec Empire." },
  { id: 179, fact: "A group of crows is called a murder." },
  { id: 180, fact: "The longest English word is 189,819 letters long." },
  { id: 181, fact: "The world's oldest piece of chewing gum is over 9,000 years old." },
  { id: 182, fact: "Peanuts are not nuts, they are legumes." },
  { id: 183, fact: "A baby puffin is called a puffling." },
  { id: 184, fact: "A single strand of spaghetti is called a spaghetto." },
  { id: 185, fact: "Ketchup was sold in the 1830s as medicine." },
  { id: 186, fact: "A group of flamingos is called a flamboyance." },
  { id: 187, fact: "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of iron." },
  { id: 188, fact: "Polar bears have black skin under their white fur." },
  { id: 189, fact: "The first oranges weren't orange." },
  { id: 190, fact: "There's a single mega-colony of ants that spans three continents." },
  { id: 191, fact: "Wombat poop is cube-shaped." },
  { id: 192, fact: "Oxford University is older than the Aztec Empire." },
  { id: 193, fact: "A group of crows is called a murder." },
  { id: 194, fact: "The longest English word is 189,819 letters long." },
  { id: 195, fact: "The world's oldest piece of chewing gum is over 9,000 years old." },
  { id: 196, fact: "Peanuts are not nuts, they are legumes." },
  { id: 197, fact: "A baby puffin is called a puffling." },
  { id: 198, fact: "A single strand of spaghetti is called a spaghetto." },
  { id: 199, fact: "Ketchup was sold in the 1830s as medicine." },
  { id: 200, fact: "A group of flamingos is called a flamboyance." },
  ];
  

  export function getRandomFact(): string {
    const randomIndex = Math.floor(Math.random() * uselessFacts.length);
    return uselessFacts[randomIndex].fact;
  }